import "../styles/globals.css"

import type { AppProps } from "next/app"
import Head from "next/head"
import React from "react"
import { createTheme, CssBaseline, ThemeProvider } from "@mui/material"
import Bar from "../src/components/Bar"
import { amber } from "@mui/material/colors"

function MyApp({ Component, pageProps }: AppProps) {
  const darkTheme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: amber[900],
      },
    },
  })
  return (
    <ThemeProvider theme={darkTheme}>
      <Head>
        <title>HiLo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <CssBaseline />

      <Bar />
      <div id="app">
        <Component {...pageProps} />
      </div>
    </ThemeProvider>
  )
}
export default MyApp
